In [1]:
# The following code includes SVM classifier
# best parameters are identified using grid search with cross validation

In [2]:
import os
print (os.getcwd())
# os.chdir("C:\Digital Nest\Decision Trees")
# print (os.getcwd())

D:\Teaching\Python-Tutorial\notebooks


In [3]:
import numpy as np
import pandas as pd
churn = pd.read_csv('../data/Churn.csv')
churn.describe()

AccountLength     AreaCode     IntlPlan    VMailPlan  VMailMessage  \
count    3333.000000  3333.000000  3333.000000  3333.000000   3333.000000   
mean      101.064806   437.182418     0.096910     0.276628      8.099010   
std        39.822106    42.371290     0.295879     0.447398     13.688365   
min         1.000000   408.000000     0.000000     0.000000      0.000000   
25%        74.000000   408.000000     0.000000     0.000000      0.000000   
50%       101.000000   415.000000     0.000000     0.000000      0.000000   
75%       127.000000   510.000000     0.000000     1.000000     20.000000   
max       243.000000   510.000000     1.000000     1.000000     51.000000   

           DayMins     DayCalls    DayCharge      EveMins     EveCalls  \
count  3333.000000  3333.000000  3333.000000  3333.000000  3333.000000   
mean    179.775098   100.435644    30.562307   200.980348   100.114311   
std      54.467389    20.069084     9.259435    50.713844    19.922625   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%     143.700000    87.000000    24.430000   166.600000    87.000000   
50%     179.400000   101.000000    30.500000   201.400000   100.000000   
75%     216.400000   114.000000    36.790000   235.300000   114.000000   
max     350.800000   165.000000    59.640000   363.700000   170.000000   

         EveCharge    NightMins   NightCalls  NightCharge     IntlMins  \
count  3333.000000  3333.000000  3333.000000  3333.000000  3333.000000   
mean     17.083540   200.872037   100.107711     9.039325    10.237294   
std       4.310668    50.573847    19.568609     2.275873     2.791840   
min       0.000000    23.200000    33.000000     1.040000     0.000000   
25%      14.160000   167.000000    87.000000     7.520000     8.500000   
50%      17.120000   201.200000   100.000000     9.050000    10.300000   
75%      20.000000   235.300000   113.000000    10.590000    12.100000   
max      30.910000   395.000000   175.000000    17.770000    20.000000   

         IntlCalls   IntlCharge  CusServCalls        Churn  
count  3333.000000  3333.000000   3333.000000  3333.000000  
mean      4.479448     2.764581      1.562856     0.144914  
std       2.461214     0.753773      1.315491     0.352067  
min       0.000000     0.000000      0.000000     0.000000  
25%       3.000000     2.300000      1.000000     0.000000  
50%       4.000000     2.780000      1.000000     0.000000  
75%       6.000000     3.270000      2.000000     0.000000  
max      20.000000     5.400000      9.000000     1.000000

In [4]:
# target class ratio
np.unique(churn.Churn,return_counts=True)

(array([0, 1], dtype=int64), array([2850,  483]))

In [5]:
2850/(2850+483)

0.8550855085508551

In [6]:
churn.columns.values

array(['State', 'AccountLength', 'AreaCode', 'Phone', 'IntlPlan',
       'VMailPlan', 'VMailMessage', 'DayMins', 'DayCalls', 'DayCharge',
       'EveMins', 'EveCalls', 'EveCharge', 'NightMins', 'NightCalls',
       'NightCharge', 'IntlMins', 'IntlCalls', 'IntlCharge',
       'CusServCalls', 'Churn'], dtype=object)

In [7]:
# check if any NA values
churn.isnull().values.any()

False

In [8]:
# find out corrleation between day charge and day minutes
np.corrcoef(churn.DayMins,churn.DayCharge)

array([[1.        , 0.99999995],
       [0.99999995, 1.        ]])

In [9]:
np.corrcoef(churn.EveMins,churn.EveCharge)

array([[1.        , 0.99999978],
       [0.99999978, 1.        ]])

In [ ]:
np.corrcoef(churn.NightMins,churn.NightCharge)

array([[1.        , 0.99999921],
       [0.99999921, 1.        ]])

In [ ]:
np.corrcoef(churn.IntlMins,churn.IntlCharge)

array([[1.        , 0.99999274],
       [0.99999274, 1.        ]])

In [ ]:
np.corrcoef(churn.DayCalls,churn.DayCharge)

array([[1.        , 0.00675296],
       [0.00675296, 1.        ]])

In [ ]:
# split the file into Independent and dependent variables
churnY = churn.iloc[::,20]
print(churnY.describe())
churnX = churn
churnX.drop(columns=['Churn','Phone'],axis=1,inplace=True)
print(churnX.shape)

count    3333.000000
mean        0.144914
std         0.352067
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000
Name: Churn, dtype: float64
(3333, 19)


In [ ]:
# splitting the data into Train and Test
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(churnX, churnY, test_size = 0.30, 
                                                    random_state = 0)
print(type(X_train))
print(type(Y_train))
print(type(X_test))
print(type(Y_test))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [ ]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(2333, 19)
(2333,)
(1000, 19)
(1000,)


In [ ]:
np.unique(churn.AreaCode,return_counts=True)

(array([408, 415, 510], dtype=int64), array([ 838, 1655,  840]))

In [ ]:
np.unique(churn.State,return_counts=True)

(array(['AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA',
        'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME',
        'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM',
        'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX',
        'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY'], dtype=object),
 array([ 52,  80,  55,  64,  34,  66,  74,  54,  61,  63,  54,  53,  44,
         73,  58,  71,  70,  59,  51,  65,  70,  62,  73,  84,  63,  65,
         68,  68,  62,  61,  56,  68,  62,  66,  83,  78,  61,  78,  45,
         65,  60,  60,  53,  72,  72,  77,  73,  66,  78, 106,  77]))

In [ ]:
np.unique(X_train.State,return_counts=True)

(array(['AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA',
        'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME',
        'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM',
        'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX',
        'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY'], dtype=object),
 array([43, 53, 44, 41, 20, 45, 53, 38, 47, 44, 42, 38, 33, 51, 35, 47, 54,
        39, 32, 46, 43, 46, 51, 61, 44, 45, 53, 41, 42, 47, 41, 42, 48, 44,
        58, 55, 48, 57, 29, 46, 46, 43, 36, 45, 46, 57, 43, 48, 57, 68, 58]))

In [ ]:
# lable encoding for strings - state
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X_train.State = le.fit_transform(X_train.State)
X_test.State = le.transform(X_test.State)
print(X_train.State.describe())

count    2333.000000
mean       25.949850
std        14.840968
min         0.000000
25%        13.000000
50%        26.000000
75%        39.000000
max        50.000000
Name: State, dtype: float64


E:\Python\Python3.7.2\lib\site-packages\pandas\core\generic.py:4405: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value


In [ ]:
#dir(LabelEncoder)

In [ ]:
np.unique(X_train.State,return_counts=True)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]),
 array([43, 53, 44, 41, 20, 45, 53, 38, 47, 44, 42, 38, 33, 51, 35, 47, 54,
        39, 32, 46, 43, 46, 51, 61, 44, 45, 53, 41, 42, 47, 41, 42, 48, 44,
        58, 55, 48, 57, 29, 46, 46, 43, 36, 45, 46, 57, 43, 48, 57, 68, 58]))

In [ ]:
X_train.columns.values

array(['State', 'AccountLength', 'AreaCode', 'IntlPlan', 'VMailPlan',
       'VMailMessage', 'DayMins', 'DayCalls', 'DayCharge', 'EveMins',
       'EveCalls', 'EveCharge', 'NightMins', 'NightCalls', 'NightCharge',
       'IntlMins', 'IntlCalls', 'IntlCharge', 'CusServCalls'],
      dtype=object)

In [ ]:
X_train.shape

(2333, 19)

In [ ]:
# apply one hot encoding on state and area
from sklearn.preprocessing import OneHotEncoder
categories = np.array([17,18])                 # column 17 - state, 18 - area code
OHE = OneHotEncoder(sparse = False, handle_unknown = 'ignore')
X_train = OHE.fit_transform(X_train)
X_test = OHE.transform(X_test)
print(X_train.shape)
print(X_test.shape)

(2333, 8584)
(1000, 8584)


In [ ]:
# type(X_train)
type(Y_train)

pandas.core.series.Series

In [ ]:
# SVM
from sklearn.svm import SVC
SVM = SVC(class_weight='balanced',degree=2,probability=True)

# build grid search parameters
parms = {'C': [0.5,2],
         'gamma':[0.2,0.9],
         'kernel': ["poly","rbf"]}
# perform grid search
from sklearn.model_selection import GridSearchCV
CV = GridSearchCV(estimator = SVM,param_grid = parms, scoring = 'roc_auc',cv=2,refit=True,
                           return_train_score = True,verbose=10,n_jobs=None)
CV.fit(X_train,Y_train)

Fitting 2 folds for each of 8 candidates, totalling 16 fits
[CV] C=0.5, gamma=0.2, kernel=poly ...................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV]  C=0.5, gamma=0.2, kernel=poly, score=(train=1.000, test=0.749), total= 3.0min
[CV] C=0.5, gamma=0.2, kernel=poly ...................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  3.4min remaining:    0.0s


[CV]  C=0.5, gamma=0.2, kernel=poly, score=(train=1.000, test=0.732), total= 2.8min
[CV] C=0.5, gamma=0.2, kernel=rbf ....................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:  6.7min remaining:    0.0s


[CV]  C=0.5, gamma=0.2, kernel=rbf, score=(train=1.000, test=0.716), total= 2.8min
[CV] C=0.5, gamma=0.2, kernel=rbf ....................................


[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed: 10.0min remaining:    0.0s


[CV]  C=0.5, gamma=0.2, kernel=rbf, score=(train=1.000, test=0.743), total= 2.9min
[CV] C=0.5, gamma=0.9, kernel=poly ...................................


[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed: 13.3min remaining:    0.0s


[CV]  C=0.5, gamma=0.9, kernel=poly, score=(train=1.000, test=0.749), total= 2.8min
[CV] C=0.5, gamma=0.9, kernel=poly ...................................


[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed: 16.5min remaining:    0.0s


[CV]  C=0.5, gamma=0.9, kernel=poly, score=(train=1.000, test=0.732), total= 2.8min
[CV] C=0.5, gamma=0.9, kernel=rbf ....................................


[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed: 19.7min remaining:    0.0s


[CV]  C=0.5, gamma=0.9, kernel=rbf, score=(train=1.000, test=0.632), total= 3.0min
[CV] C=0.5, gamma=0.9, kernel=rbf ....................................


[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed: 23.3min remaining:    0.0s


[CV]  C=0.5, gamma=0.9, kernel=rbf, score=(train=1.000, test=0.635), total= 3.2min
[CV] C=2, gamma=0.2, kernel=poly .....................................


[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed: 26.9min remaining:    0.0s


[CV]  C=2, gamma=0.2, kernel=poly, score=(train=1.000, test=0.749), total= 2.5min
[CV] C=2, gamma=0.2, kernel=poly .....................................


[Parallel(n_jobs=1)]: Done   9 out of   9 | elapsed: 29.8min remaining:    0.0s


[CV]  C=2, gamma=0.2, kernel=poly, score=(train=1.000, test=0.732), total= 2.5min
[CV] C=2, gamma=0.2, kernel=rbf ......................................
[CV]  C=2, gamma=0.2, kernel=rbf, score=(train=1.000, test=0.723), total= 2.6min
[CV] C=2, gamma=0.2, kernel=rbf ......................................
[CV]  C=2, gamma=0.2, kernel=rbf, score=(train=1.000, test=0.745), total= 2.6min
[CV] C=2, gamma=0.9, kernel=poly .....................................


In [ ]:
%%time
CVResults = pd.DataFrame(CV.cv_results_)
print(CVResults)
# CVResults.to_excel('../data/CVResutls_SVM.xlsx')

In [ ]:
print(CV.best_estimator_)

In [ ]:
print(CV.best_score_)
print(CV.best_params_)

In [ ]:
# Preidct on Test data and check the confusion matrix
predictTest = CV.predict(X_test)
print(predictTest[0:10])

In [ ]:
predictProb = CV.predict_proba(X_test)
print(predictProb[0:10])
PProb = pd.DataFrame(predictProb)

In [ ]:
# generate confusion matrix
# import confusion matrix and classification report
from sklearn.metrics import confusion_matrix, classification_report
print (confusion_matrix(Y_test,predictTest))
print (classification_report(Y_test,predictTest))

In [ ]:
# generate ROC curve
from sklearn.metrics import roc_auc_score, roc_curve
# AUC for class 1
AUC = roc_auc_score(Y_test, PProb[0])
print(AUC)
# AUC for class 0
AUC0 = roc_auc_score(Y_test, PProb[0])
print(AUC0)
# define variables for True Positive Rate and Falst Positive Rate & threshold value
TPR = dict()
FPR = dict()
THR = dict()
FPR, TPR, THR = roc_curve(Y_test, PProb[1])

In [ ]:
print(THR)
print(TPR)
print(FPR)

In [ ]:
import matplotlib.pyplot as plt
plt.figure()
# plot the FPR as X-axis and TPR as Y-axis
plt.plot(FPR, TPR)
# plot the minimum line 
plt.plot([0,1], [0,1], color='navy', linestyle = '--')
# set X and Y limits
plt.xlim([0.0, 1.05])
plt.ylim([0.0, 1.05])
# mention lables for X and Y
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC')
plt.show()